// Lapa la Pholoma - 25 Members - SEPARATED Lapa la Sepuru
const members = [
  {id:1, first:"Pholoma", last:"Sepuru", surname:"Sepuru", gender:"M", gen:1, aka:"", note:"", lapa:"Lapa la Sepuru", bio:"Tate - Root"},
  {id:2, first:"Ngwana Mahoai", last:"", surname:"", gender:"F", gen:1, aka:"", note:"", lapa:"Lapa la Sepuru", bio:"Mme - mosadi wa Pholoma"},
  {id:3, first:"Makgabo Sekutu", last:"Sepuru", surname:"Sepuru", gender:"F", gen:2, aka:"Raesetja", note:"Lapa la ga Sekuto", lapa:"Lapa la ga Sekuto", bio:"Le lengwe ke Raesetja"},
  {id:4, first:"Mmanare Chokoe", last:"Sepuru", surname:"Sepuru", gender:"F", gen:2, aka:"", note:"bommago Thabitha", lapa:"Lapa la Sepuru", bio:"Bommago Thabitha"},
  {id:5, first:"Leka Lesiba", last:"Sepuru", surname:"Sepuru", gender:"F", gen:2, aka:"Lesiba", note:"L e tee - malapa a mabedi", lapa:"Lleka wa re malapa ao a mabedi", bio:"Malapa a mabedi - basadi ba 2"},
  {id:6, first:"Tshwene", last:"Sepuru", surname:"Sepuru", gender:"M", gen:2, aka:"", note:"wa go timela", lapa:"Ga a na bana", bio:"Wa go timela - ga a na bana"},
  {id:7, first:"Mmakomana wa ga Pula", last:"Sepuru", surname:"Sepuru", gender:"F", gen:2, aka:"", note:"wa ga Pula", lapa:"Lapa la ga Pula ga Setati", bio:"Wa ga Pula"},
  {id:8, first:"Raisibe", last:"Sepuru", surname:"Sepuru", gender:"F", gen:2, aka:"", note:"", lapa:"Lapa la ga Chokwe Setupulane", bio:""},
  {id:9, first:"Mmatšhwene wa Chokoe", last:"Sepuru", surname:"Sepuru", gender:"F", gen:2, aka:"Non Parel", note:"Non Parel", lapa:"Chokwe Nobral", bio:"Non Parel"},
  {id:10, first:"Thabitha", last:"Sepuru", surname:"Sepuru", gender:"F", gen:3, aka:"", note:"ngwana wa Mmanare", lapa:"", bio:"Ngwana wa Mmanare Chokoe"},
  {id:11, first:"Mokgaetsi Flora", last:"Pula", surname:"Pula", gender:"F", gen:3, aka:"", note:"", lapa:"Lapa la Pula", bio:"Ngwana wa Mmakomana"},
  {id:12, first:"Pholoma Helen", last:"Semenya", surname:"Semenya", gender:"F", gen:3, aka:"", note:"", lapa:"Lapa la Pula", bio:"Ngwana wa Mmakomana"},
  {id:13, first:"Regina Molatelo", last:"Pula", surname:"Pula", gender:"F", gen:3, aka:"", note:"", lapa:"Lapa la Pula", bio:"Ngwana wa Mmakomana"},
  {id:14, first:"Thabitha Mmakwena", last:"Pula", surname:"Pula", gender:"F", gen:3, aka:"", note:"", lapa:"Lapa la Pula", bio:"Ngwana wa Mmakomana"},
  {id:15, first:"Maria", last:"Pula", surname:"Pula", gender:"F", gen:3, aka:"", note:"", lapa:"Lapa la Pula", bio:"Ngwana wa Mmakomana"},
  {id:16, first:"Maria Mmanoko", last:"Pula", surname:"Pula", gender:"F", gen:3, aka:"", note:"", lapa:"Lapa la Pula", bio:"Ngwana wa Mmakomana"},
  {id:17, first:"Ngwana", last:"Moloto", surname:"Moloto", gender:"F", gen:3, aka:"", note:"mosadi wa Leka", lapa:"Lapa la Leka - Moloto", bio:"Mosadi wa Leka"},
  {id:18, first:"Ngwana", last:"Chokoe", surname:"Chokoe", gender:"F", gen:3, aka:"", note:"mosadi wa Leka", lapa:"Lapa la Leka - Chokoe", bio:"Mosadi wa Leka"},
  {id:19, first:"Rahab Kwena", last:"Mphago", surname:"Mphago", gender:"F", gen:4, aka:"", note:"", lapa:"", bio:"Ngwana wa Leka le Moloto"},
  {id:20, first:"Daniel Pholoma", last:"Sepuru", surname:"Sepuru", gender:"M", gen:4, aka:"", note:"", lapa:"", bio:"Ngwana wa Leka le Moloto"},
  {id:21, first:"Welhemina Mokgoba", last:"Rangata", surname:"Rangata", gender:"F", gen:4, aka:"", note:"", lapa:"", bio:"Ngwana wa Leka le Moloto"},
  {id:22, first:"Jostina Makgabo", last:"Mokgehle", surname:"Mokgehle", gender:"F", gen:4, aka:"", note:"", lapa:"", bio:"Ngwana wa Leka le Moloto"},
  {id:23, first:"Jonas Matjentje", last:"Sepuru", surname:"Sepuru", gender:"M", gen:4, aka:"", note:"", lapa:"", bio:"Ngwana wa Leka le Moloto"},
  {id:24, first:"Phillimon Manai", last:"Sepuru", surname:"Sepuru", gender:"M", gen:4, aka:"", note:"", lapa:"", bio:"Ngwana wa Leka le Moloto"},
  {id:25, first:"Jackson Mokibelo", last:"Sepuru", surname:"Sepuru", gender:"M", gen:4, aka:"", note:"", lapa:"", bio:"Ngwana wa Leka le Moloto"},

  {id:26, first:"Phineas Lesiba", last:"Sepuru", surname:"Sepuru", gender:"M", gen:3, aka:"", note:"ko Setupulane", lapa:"Lapa la ga Chokwe Setupulane", bio:"Ngwana wa Raisibe - ko Setupulane"},
  {id:27, first:"Esther", last:"Ngwetjana", surname:"Ngwetjana", gender:"F", gen:3, aka:"", note:"ko Prospect", lapa:"Lapa la Ngwetjana", bio:"Ngwana wa Raisibe - ko Prospect"},
  {id:28, first:"Solomon Lesetja", last:"Sepuru", surname:"Sepuru", gender:"M", gen:3, aka:"", note:"ko Rammobola", lapa:"Lapa la ga Chokwe Setupulane", bio:"Ngwana wa Raisibe - ko Rammobola"},
  {id:29, first:"Solomon Kgabo", last:"Sekuto", surname:"Sekuto", gender:"M", gen:3, aka:"", note:"ko Burgwal papago Jack", lapa:"Lapa la ga Sekuto", bio:"Ngwana wa Makgabo Sekuto - ko Burgwal papago Jack"},
  {id:30, first:"Gilbert", last:"Sekuto", surname:"Sekuto", gender:"M", gen:3, aka:"", note:"ko Moletji", lapa:"Lapa la ga Sekuto", bio:"Ngwana wa Makgabo Sekuto - ko Moletji"},
  {id:31, first:"Esther", last:"Sekuto", surname:"Sekuto", gender:"F", gen:3, aka:"", note:"mmago Mpuleng", lapa:"Lapa la ga Sekuto", bio:"Ngwana wa Makgabo Sekuto - mmago Mpuleng"},

];
const relationships = [
  {p:1,c:3},{p:2,c:3},{p:1,c:4},{p:2,c:4},{p:1,c:5},{p:2,c:5},{p:1,c:6},{p:2,c:6},{p:1,c:7},{p:2,c:7},{p:1,c:8},{p:2,c:8},{p:1,c:9},{p:2,c:9},
  {p:4,c:10},{p:7,c:11},{p:7,c:12},{p:7,c:13},{p:7,c:14},{p:7,c:15},{p:7,c:16},
  {p:5,c:17,type:"spouse"},{p:5,c:18,type:"spouse"},
  {p:5,c:19},{p:17,c:19},{p:5,c:20},{p:17,c:20},{p:5,c:21},{p:17,c:21},{p:5,c:22},{p:17,c:22},{p:5,c:23},{p:17,c:23},{p:5,c:24},{p:17,c:24},{p:5,c:25},{p:17,c:25},
  {p:8,c:26},{p:8,c:27},{p:8,c:28},
  {p:3,c:29},{p:3,c:30},{p:3,c:31},
];
